exports.firebaseCollections = Object.freeze({
    STUDENTS: "students",
    PARENTS: "parents",
    USERS: "users",
    SUBJECTS: "subjects",
    DOCUMENTS: "documents",
    DOCUMENT_TEMPLATES: "document_templates",
    DOCUMENT_LAYOUTS: "document_layouts",
    DOCUMENT_VERSIONS: "document_versions",
    STORAGES: "storages",
    SUMMARY_DATA: "summary_data",
    GRANULAR_PERMISSIONS: "granular_permissions",
    PERMISSIONS: "users_permissions",
    GLOBAL_PERMISSIONS: "global_permissions",
    GLOBAL_DOCUMENT_PERMISSIONS: "global_document_permissions",
    DOCUMENT_PERMISSIONS: "document_permissions",
    LAYOUT_PERMISSIONS: "layout_permissions",
    ALL_DOCUMENT_PERMISSIONS: "all_document_permissions",
    OCCUPATIONS_ENUM: "occupations_enum",
    STORAGE_LOGS: "storage_logs",
    SUBJECT_STUDENTS: "subject_students",
    SUBJECT_PROFESSORS: "subject_professors"
});